# workflow 的名称
name: "demo-ci"

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [ "main" ]

  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          pwd
          go version

      - name: clone respositry
        uses: actions/checkout@v4
  
      - name: compile
        run: |
          pwd
          ls -lh
          go build -o ./app .
  run:
    runs-on: ubuntu-latest
    needs:
      - build # 依赖build这个job
    steps:
      - name: run app
        run: |
          pwd
          ls -lh
          ./app

